package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "find_route",
    srcs = ["find_route.cc"],
    deps = [
        "//common/utils/file",
        "//homework4/display:main_window",
        "//homework4/map:map_lib",
        "@gflags//:gflags",
        "@glog",
    ],
)