package(default_visibility = ["//visibility:public"])

cc_library(
    name = "agents",
    srcs = ["agents.cc"],
    hdrs = ["agents.h"],
    deps = [
        "//homework5/agents/sample:sample_agent",
        "//homework5/agents/nbt:nbt_agent",
        "//homework5/simulation:vehicle_agent_factory",
    ],
    alwayslink = 1,
)
